export const GET_SUCCESS="GET_SUCCESS";
export const GET_ERROR="GET_ERROR";
export const GET_REQUEST="GET_REQUEST"; 

export const POST_SUCCESS="POST_SUCCESS";
export const POST_ERROR="POST_ERROR";
export const POST_REQUEST="POST_REQUEST"; 

export const PATCH_SUCCESS="PATCH_SUCCESS";
export const PATCH_ERROR="PATCH_ERROR";
export const PATCH_REQUEST="PATCH_REQUEST"; 

export const DELETE_SUCCESS="DELETE_SUCCESS";
export const DELETE_ERROR="DELETE_ERROR";
export const DELETE_REQUEST="DELETE_REQUEST"; 